version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "markselyukov123456789"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-k9j9erfl0ps2"
s3_prefix = "markselyukov123456789"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
